module_0:
  class: LinearRegression
  module: sklearn.linear_model
  params:
    fit_intercept: true
  search_param_grid:
    fit_intercept:
    - true
    - false
module_1:
  class: RandomForestRegressor
  module: sklearn.ensemble
  params:
    min_samples_leaf: 3
  search_param_grid:
    min_samples_leaf:
    - 4
